In [2]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

2024-04-02 20:56:56.495004: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-02 20:56:56.657510: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-02 20:56:56.657622: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [11]:
c = tf.constant([[1.0, 4., 3., 2.0], [3.0, 4., 4., 4.0]])

In [20]:
print(c)
batch_size = 2
dims = 4
begin = 1

mu = tf.slice(c, [0, 0], [batch_size, 1])
cov = tf.slice(c, [0, begin], [batch_size, dims-begin])

print(mu)
print(cov)

tf.Tensor(
[[1. 4. 3. 2.]
 [3. 4. 4. 4.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1.]
 [3.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[4. 3. 2.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)


In [4]:
import sys; sys.path.insert(1, '..')
import utility

In [2]:

import pandas as pd

pricesDataFolder = "../prices_data/"
dfH4 = pd.read_csv(
    filepath_or_buffer=pricesDataFolder+"H4/[SP500]_H4_2014-03-20__2024-03-20.csv",
    delimiter="\t"
)

dfH4 = dfH4.rename(
    columns = {
        '<OPEN>':'open', 
        '<HIGH>':'high', 
        '<LOW>':'low', 
        '<CLOSE>':'close'
    }
)

print(f'dfH4 index: {dfH4.index}')

dfH4 index: RangeIndex(start=0, stop=15426, step=1)


In [14]:
from random import choice
longTermMAPeriod = 200
strategyN = 3
startIndex = choice(dfH4.index[longTermMAPeriod+strategyN: -100])
i = 120
nbrCandles = 10
observation = dfH4[["open", "close","low", "high"]].loc[startIndex-nbrCandles+i:startIndex+i]
print(f"strat index: {startIndex}")
print("==========================================")
print(observation)
print("==========================================")
print(observation.loc[startIndex+i])


strat index: 3236
        open   close     low    high
3346  2044.8  2039.8  2038.9  2045.5
3347  2039.6  2037.2  2036.1  2042.7
3348  2037.1  2039.4  2036.5  2044.3
3349  2039.5  2027.9  2025.3  2043.1
3350  2028.1  2042.0  2027.9  2042.2
3351  2042.1  2047.4  2040.7  2047.7
3352  2047.3  2047.9  2045.1  2049.0
3353  2048.0  2048.9  2045.4  2050.4
3354  2048.6  2048.4  2044.1  2048.9
3355  2047.9  2055.7  2046.2  2058.9
3356  2055.3  2052.2  2048.4  2056.3
open     2055.3
close    2052.2
low      2048.4
high     2056.3
Name: 3356, dtype: float64


In [62]:
import tensorflow as tf
import numpy as np
from tensorflow.python.keras.activations import softmax
import math
import tensorflow_probability as tfp

# a = tf.constant([1, 2, 2, 6])
# b = tf.constant([[1, 4, 3, 2]])
# c = tf.constant([[1], [4], [3], [2]])

# print(a)
# print(b)
# print(c)


# a = tf.expand_dims(a, axis=0)
# print(a)

# print(tf.concat([a,b], axis=1))
input = tf.constant([[1.89, 3.222, 2.611]])
mask = np.array([[True, False, True]])

print(input)
print(mask.shape)

output = tf.where(mask, input, -math.inf)
print(output)
output = softmax(output)
print(output)
print(f"sum of probabilities: {tf.reduce_sum(output)}")
dist = tfp.distributions.Categorical(probs=output)

dist.sample()

# def softmax_filtered(input, mask):
#     return softmax(tf.where(mask, input, -math.inf))


tf.Tensor([[1.89  3.222 2.611]], shape=(1, 3), dtype=float32)
(1, 3)
tf.Tensor([[1.89   -inf 2.611]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.3271728  0.         0.67282724]], shape=(1, 3), dtype=float32)
sum of probabilities: 1.0


<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [63]:
l = [1,2,3]
sum(l)

6

In [10]:
from datetime import datetime, timedelta
timestamp = 1712681006632.0/1000.0
datetime_object = dt_object = datetime.fromtimestamp(timestamp)

datetime_object.timestamp()

1712681006.632

In [13]:
import numpy as np

arr = np.array([[5,6,9],[1,2,5],[-6,-3,-14]])
print(arr)
print(arr[0,-1])
print(arr[:,-1])
# print(arr[:])
print(arr[2,0])

[[  5   6   9]
 [  1   2   5]
 [ -6  -3 -14]]
9
[  9   5 -14]
-6


In [2]:
l = [1,2,3,4]
print(*l)

1 2 3 4


In [1]:
import sys; sys.path.insert(1, '..')
from reinforcement_learning.trading_agent.actor_critic.encoderTransformerNetwork import Encoder

params={ 'sequence_length':100, 'h':4, 'd_k':1, 'd_v':1, 'd_model':4, 'd_ff':128, 'n':6}

encoder = Encoder(**params)

2024-04-23 21:11:59.283705: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-23 21:11:59.991588: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-04-23 21:12:00.796199: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-23 21:12:00.836820: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-23 21:12:00.836870: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] co

lentgh 4
lentgh 100
depths (1, 2)
positions (100, 1)
pos_encoding (100, 4)


In [2]:
import numpy as np

_input = np.random.rand(1,100,4)
print(_input.shape)


(1, 100, 4)


In [3]:

_output = encoder(_input)
print(_output)

x shape: [  1 100   4]
tf.Tensor(
[[[-1.4179502   1.4047905   0.08263968 -0.06948001]
  [-0.8733837  -0.44022352  1.6999629  -0.3863557 ]
  [ 0.04533879 -0.877519   -0.78344315  1.6156235 ]
  [ 0.06240699 -1.0023685  -0.6582653   1.5982268 ]
  [-0.9737877   1.6721687  -0.4107124  -0.2876687 ]
  [-1.1981156   1.4712098   0.28636467 -0.55945903]
  [-0.9749132   0.74448025  1.2247218  -0.99428886]
  [-1.4945066  -0.29851222  0.71417034  1.0788485 ]
  [-0.8645055  -0.33989722  1.6992936  -0.49489108]
  [ 0.42328405 -0.59016436 -1.2307316   1.3976119 ]
  [-1.2577038   1.0009317  -0.70195675  0.9587289 ]
  [-1.2962      1.4516801   0.23499231 -0.39047226]
  [-1.5880182   1.1776848   0.2424987   0.16783464]
  [ 0.5041312  -1.4309167   1.2590396  -0.33225414]
  [ 0.83231753 -0.69460225 -1.2544358   1.1167204 ]
  [ 0.17532976  1.4918977  -1.2512976  -0.41592985]
  [-0.04328723  1.6373721  -0.65181965 -0.94226533]
  [-0.9796258   1.6030552   0.05667666 -0.680106  ]
  [-1.186846    1.5755085  -0.

In [2]:
import tensorflow as tf
tf.math.sigmoid(0.3)

2024-04-24 18:25:56.232814: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-24 18:25:56.924451: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-04-24 18:25:57.549181: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-24 18:25:57.574803: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-24 18:25:57.574853: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] co

<tf.Tensor: shape=(), dtype=float32, numpy=0.5744425>