In [2]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

2024-04-02 20:56:56.495004: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-02 20:56:56.657510: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-02 20:56:56.657622: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [11]:
c = tf.constant([[1.0, 4., 3., 2.0], [3.0, 4., 4., 4.0]])

In [20]:
print(c)
batch_size = 2
dims = 4
begin = 1

mu = tf.slice(c, [0, 0], [batch_size, 1])
cov = tf.slice(c, [0, begin], [batch_size, dims-begin])

print(mu)
print(cov)

tf.Tensor(
[[1. 4. 3. 2.]
 [3. 4. 4. 4.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1.]
 [3.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[4. 3. 2.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)


In [4]:
import sys; sys.path.insert(1, '..')
import utility

In [2]:

import pandas as pd

pricesDataFolder = "../prices_data/"
dfH4 = pd.read_csv(
    filepath_or_buffer=pricesDataFolder+"H4/[SP500]_H4_2014-03-20__2024-03-20.csv",
    delimiter="\t"
)

dfH4 = dfH4.rename(
    columns = {
        '<OPEN>':'open', 
        '<HIGH>':'high', 
        '<LOW>':'low', 
        '<CLOSE>':'close'
    }
)

print(f'dfH4 index: {dfH4.index}')

dfH4 index: RangeIndex(start=0, stop=15426, step=1)


In [14]:
from random import choice
longTermMAPeriod = 200
strategyN = 3
startIndex = choice(dfH4.index[longTermMAPeriod+strategyN: -100])
i = 120
nbrCandles = 10
observation = dfH4[["open", "close","low", "high"]].loc[startIndex-nbrCandles+i:startIndex+i]
print(f"strat index: {startIndex}")
print("==========================================")
print(observation)
print("==========================================")
print(observation.loc[startIndex+i])


strat index: 3236
        open   close     low    high
3346  2044.8  2039.8  2038.9  2045.5
3347  2039.6  2037.2  2036.1  2042.7
3348  2037.1  2039.4  2036.5  2044.3
3349  2039.5  2027.9  2025.3  2043.1
3350  2028.1  2042.0  2027.9  2042.2
3351  2042.1  2047.4  2040.7  2047.7
3352  2047.3  2047.9  2045.1  2049.0
3353  2048.0  2048.9  2045.4  2050.4
3354  2048.6  2048.4  2044.1  2048.9
3355  2047.9  2055.7  2046.2  2058.9
3356  2055.3  2052.2  2048.4  2056.3
open     2055.3
close    2052.2
low      2048.4
high     2056.3
Name: 3356, dtype: float64


In [4]:
import tensorflow as tf
a = tf.constant([1, 2, 2, 6])
b = tf.constant([[1, 4, 3, 2]])
print(a)
print(b)

a = tf.expand_dims(a, axis=0)
print(a)

print(tf.concat([a,b], axis=1))

tf.Tensor([1 2 2 6], shape=(4,), dtype=int32)
tf.Tensor([[1 4 3 2]], shape=(1, 4), dtype=int32)
tf.Tensor([[1 2 2 6]], shape=(1, 4), dtype=int32)
tf.Tensor([[1 2 2 6 1 4 3 2]], shape=(1, 8), dtype=int32)


In [10]:
from datetime import datetime
timestamp = 1712681006632.0/1000.0
datetime_object = dt_object = datetime.fromtimestamp(timestamp)

datetime_object.timestamp()

1712681006.632