In [2]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

2024-04-02 20:56:56.495004: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-02 20:56:56.657510: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-02 20:56:56.657622: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [11]:
c = tf.constant([[1.0, 4., 3., 2.0], [3.0, 4., 4., 4.0]])

In [20]:
print(c)
batch_size = 2
dims = 4
begin = 1

mu = tf.slice(c, [0, 0], [batch_size, 1])
cov = tf.slice(c, [0, begin], [batch_size, dims-begin])

print(mu)
print(cov)

tf.Tensor(
[[1. 4. 3. 2.]
 [3. 4. 4. 4.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1.]
 [3.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[4. 3. 2.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)
