In [1]:
import tensorflow as tf

2024-03-31 16:06:15.737842: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-31 16:06:16.859074: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [11]:
c = tf.constant([[1.0, 4., 3., 2.0], [3.0, 4., 4., 4.0]])

In [20]:
print(c)
batch_size = 2
dims = 4
begin = 1

mu = tf.slice(c, [0, 0], [batch_size, 1])
cov = tf.slice(c, [0, begin], [batch_size, dims-begin])

print(mu)
print(cov)

tf.Tensor(
[[1. 4. 3. 2.]
 [3. 4. 4. 4.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1.]
 [3.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[4. 3. 2.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)
